### ISSUE TITLE
get_data and others elements are not define

### ISSUE THREAD

**Issue by bastiendonjon** [smileinnovation/cryptocurrency-trading#3]
I have a few errors in netbook :

NameError: name 'get_data' is not defined
NameError: name 'normalize_data' is not defined
NameError: name 'x_train' is not defined
NameError: name 'model' is not defined
NameError: name 'x_test' is not defined

**Comment by kuty22** [comment]
Hello,

The error is because the dataset is not in the repository and because the "get_data" function is not in the notebook.

The dataset is too large to be stored in the repo.
To get your own data, you can use this script https://github.com/sky54000/Scroller_bittrex_websocket_node , it gets the data and stores it in a database.

Then to use this data connect your notebook via "pymysql"  or dump and transform in CSV format.

the function get_data return this format :
```json
[
  { 
    "name": "Your market name (ex. BTC-NEO)",
    "data": "Pandas dataframe of the market"
  },
]
```

But you right, I will add some documentation about that in the notebook and in the README.md.

**Comment by bastiendonjon** [comment]
Thanks. Yes you can add a little dataset for exemple.

**Comment by kuty22** [comment]
Hello, 

I added some explanations in the documentation that can help you run the notebook.

We are not able to upload our dataset because of the file size and a small one is not a good thing.

It is not a good thing because on a little dataset the result can be disappointing, but to reproduce the same dataset than ours, you can use this software [Scroller_bittrex_websocket_node](https://github.com/sky54000/Scroller_bittrex_websocket_node).
