### ISSUE TITLE
test dataset

### ISSUE THREAD

**Issue by qxdfd** [smileinnovation/cryptocurrency-trading#4]
In the actual situation, you don't know the distribution of future data.
So maybe you should split the data before the data preprocessing.

**Comment by qxdfd** [comment]
AND
1. You set the peakmin as sell, but should be the peakmax. The same question in setting buy point.
```
def setSell(idx, peaksmax, peaksmin):
    for i in peaksmax:
        if i[0] == idx:
            return 0.0
    for i in peaksmin:
        if i[0] == idx:
            return 1.0
    return 0.0
```

2. In the part of the prediction, you insert normalize_data price but not the test set price. So you just used the prediction of test data to buy/sell the beginning of train data.
```
if prediction[:, 0] == max(prediction[0]):
        if trade_type is None and capital > 0:
            buy_invest.append((i, normalize_data["bid"].loc[i]))
            trade.append((i, normalize_data["bid"].loc[i]))
            trade_type = True
            type_price = "buy"
```

**Comment by kuty22** [comment]
Hello qxdfd,

thanks for your time and your comments. You're totally right about these two mistakes, I have pushed a fix just now. About your first advice, we indeed do not know the distribution and in a real case we must split before normalization. We don't do it in our case since we have the full dataset, and it is more effective. Our technique can't work on real markets with this data preprocessing.
